linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - gocyclo
    - dupl
    - misspell
    - revive
  settings:
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    govet:
      enable:
        - shadow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
